### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by luismiguelbravo** [bsmurphy/PyKrige#8] opened 2015-09-08 17:15 UTC
Hello, thanks for sharing

I get de error when I try

pip install pykrige

![image](https://cloud.githubusercontent.com/assets/5140529/9741949/3200e3da-5627-11e5-9436-a5cadcf798d5.png)

**Comment by rth** [comment] 2015-09-08 18:38
Hello,

what version of anaconda are you using (32bit, 64bit) and what is your OS? Also can you copy-past the full error output instead of the screenshot?

I cannot reproduce this error so far. With a new conda install (64bit on linux), running

    conda install  numpy cython scipy
    pip install pykrige

installs the package as expected.

**Comment by bsmurphy** [comment] 2015-09-08 19:08
I'm actually also getting this error on my Windows machine (running Windows 10, 64-bit). (Only checked the updates on my Mac desktop before.) Here's the full error output from my pip debug log:

```console
Getting page https://pypi.python.org/simple/pykrige/
URLs to search for versions for pykrige in c:\python27\lib\site-packages:
* https://pypi.python.org/simple/pykrige/
Analyzing links from page https://pypi.python.org/simple/pykrige/
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-0.1.1.tar.gz#md5=87c987ffa7aededb3ddbc71e352f2cf2 (from https://pypi.python.org/simple/pykrige/), version: 0.1.1
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-0.1.2.tar.gz#md5=e5e3fb39a046a930c64072c919c9f100 (from https://pypi.python.org/simple/pykrige/), version: 0.1.2
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-0.1.tar.gz#md5=806c966f983632741a7f8160a4492d94 (from https://pypi.python.org/simple/pykrige/), version: 0.1
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-0.2.0.tar.gz#md5=4c664f9e5a949da391b59bbd1c9d19f7 (from https://pypi.python.org/simple/pykrige/), version: 0.2.0
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.0.1.tar.gz#md5=002ffc1dbadc1cd7c0faaf726fa2df30 (from https://pypi.python.org/simple/pykrige/), version: 1.0.1
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.0.2.tar.gz#md5=a412c12340f8fd85702f37635976bcba (from https://pypi.python.org/simple/pykrige/), version: 1.0.2
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.0.3.tar.gz#md5=9155c64aebdfde46976ae8222ee1140d (from https://pypi.python.org/simple/pykrige/), version: 1.0.3
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.0.tar.gz#md5=796e29a4d26518a432840fedeec58072 (from https://pypi.python.org/simple/pykrige/), version: 1.0
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.1.0.tar.gz#md5=f5046b58040bdfdd332e9db9331828ef (from https://pypi.python.org/simple/pykrige/), version: 1.1.0
  Found link https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.2.0.tar.gz#md5=85dbd0c7b59f3d6a27eec094aa0fa1b0 (from https://pypi.python.org/simple/pykrige/), version: 1.2.0
Using version 1.2.0 (newest of versions: 1.2.0, 1.1.0, 1.0.3, 1.0.2, 1.0.1, 1.0, 0.2.0, 0.2.0, 0.1.2, 0.1.1, 0.1)
Downloading/unpacking pykrige from https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.2.0.tar.gz#md5=85dbd0c7b59f3d6a27eec094aa0fa1b0
  Downloading from URL https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.2.0.tar.gz#md5=85dbd0c7b59f3d6a27eec094aa0fa1b0
  Running setup.py (path:c:\users\ben\appdata\local\temp\pip_build_Ben\pykrige\setup.py) egg_info for package pykrige
    running egg_info
    creating pip-egg-info\PyKrige.egg-info
    writing pip-egg-info\PyKrige.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\PyKrige.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\PyKrige.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\PyKrige.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info\PyKrige.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info\PyKrige.egg-info\SOURCES.txt'
  Source in c:\users\ben\appdata\local\temp\pip_build_ben\pykrige has version 1.2.0, which satisfies requirement pykrige from https://pypi.python.org/packages/source/P/PyKrige/PyKrige-1.2.0.tar.gz#md5=85dbd0c7b59f3d6a27eec094aa0fa1b0
Installing collected packages: pykrige
  Found existing installation: PyKrige 0.2.0
    Uninstalling PyKrige:
      Removing file or directory c:\python27\lib\site-packages\pykrige-0.2.0-py2.7.egg-info
      Removing file or directory c:\python27\lib\site-packages\pykrige\__init__.py
      Removing file or directory c:\python27\lib\site-packages\pykrige\__init__.pyc
      Removing file or directory c:\python27\lib\site-packages\pykrige\core.py
      Removing file or directory c:\python27\lib\site-packages\pykrige\core.pyc
      Removing file or directory c:\python27\lib\site-packages\pykrige\kriging_tools.py
      Removing file or directory c:\python27\lib\site-packages\pykrige\kriging_tools.pyc
      Removing file or directory c:\python27\lib\site-packages\pykrige\ok.py
      Removing file or directory c:\python27\lib\site-packages\pykrige\ok.pyc
      Removing file or directory c:\python27\lib\site-packages\pykrige\test.py
      Removing file or directory c:\python27\lib\site-packages\pykrige\test.pyc
      Removing file or directory c:\python27\lib\site-packages\pykrige\uk.py
      Removing file or directory c:\python27\lib\site-packages\pykrige\uk.pyc
      Removing file or directory c:\python27\lib\site-packages\pykrige\variogram_models.py
      Removing file or directory c:\python27\lib\site-packages\pykrige\variogram_models.pyc
      Successfully uninstalled PyKrige
  Running setup.py install for pykrige
    Running command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\ben\\appdata\\local\\temp\\pip_build_Ben\\pykrige\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\ben\appdata\local\temp\pip-hnpeg6-record\install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\pykrige
    copying pykrige\core.py -> build\lib.win32-2.7\pykrige
    copying pykrige\kriging_tools.py -> build\lib.win32-2.7\pykrige
    copying pykrige\ok.py -> build\lib.win32-2.7\pykrige
    copying pykrige\ok3d.py -> build\lib.win32-2.7\pykrige
    copying pykrige\test.py -> build\lib.win32-2.7\pykrige
    copying pykrige\uk.py -> build\lib.win32-2.7\pykrige
    copying pykrige\uk3d.py -> build\lib.win32-2.7\pykrige
    copying pykrige\variogram_models.py -> build\lib.win32-2.7\pykrige
    copying pykrige\__init__.py -> build\lib.win32-2.7\pykrige
    creating build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test1_settings.txt -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test2_settings.txt -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test3d_answer.txt -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test3d_data.txt -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test3_settings.txt -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test_data.txt -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test1_answer.asc -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test2_answer.asc -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test3_answer.asc -> build\lib.win32-2.7\pykrige\test_data
    copying pykrige\test_data\test3_dem.asc -> build\lib.win32-2.7\pykrige\test_data
    running build_ext
    cythoning pykrige/lib/cok.pyx to pykrige/lib\cok.c
    building 'pykrige.lib.cok' extension
    error: Unable to find vcvarsall.bat
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\ben\\appdata\\local\\temp\\pip_build_Ben\\pykrige\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\ben\appdata\local\temp\pip-hnpeg6-record\install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build\lib.win32-2.7

creating build\lib.win32-2.7\pykrige

copying pykrige\core.py -> build\lib.win32-2.7\pykrige

copying pykrige\kriging_tools.py -> build\lib.win32-2.7\pykrige

copying pykrige\ok.py -> build\lib.win32-2.7\pykrige

copying pykrige\ok3d.py -> build\lib.win32-2.7\pykrige

copying pykrige\test.py -> build\lib.win32-2.7\pykrige

copying pykrige\uk.py -> build\lib.win32-2.7\pykrige

copying pykrige\uk3d.py -> build\lib.win32-2.7\pykrige

copying pykrige\variogram_models.py -> build\lib.win32-2.7\pykrige

copying pykrige\__init__.py -> build\lib.win32-2.7\pykrige

creating build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test1_settings.txt -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test2_settings.txt -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test3d_answer.txt -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test3d_data.txt -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test3_settings.txt -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test_data.txt -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test1_answer.asc -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test2_answer.asc -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test3_answer.asc -> build\lib.win32-2.7\pykrige\test_data

copying pykrige\test_data\test3_dem.asc -> build\lib.win32-2.7\pykrige\test_data

running build_ext

cythoning pykrige/lib/cok.pyx to pykrige/lib\cok.c

building 'pykrige.lib.cok' extension

error: Unable to find vcvarsall.bat

----------------------------------------
  Rolling back uninstall of PyKrige
  Replacing c:\python27\lib\site-packages\pykrige-0.2.0-py2.7.egg-info
  Replacing c:\python27\lib\site-packages\pykrige\__init__.py
  Replacing c:\python27\lib\site-packages\pykrige\__init__.pyc
  Replacing c:\python27\lib\site-packages\pykrige\core.py
  Replacing c:\python27\lib\site-packages\pykrige\core.pyc
  Replacing c:\python27\lib\site-packages\pykrige\kriging_tools.py
  Replacing c:\python27\lib\site-packages\pykrige\kriging_tools.pyc
  Replacing c:\python27\lib\site-packages\pykrige\ok.py
  Replacing c:\python27\lib\site-packages\pykrige\ok.pyc
  Replacing c:\python27\lib\site-packages\pykrige\test.py
  Replacing c:\python27\lib\site-packages\pykrige\test.pyc
  Replacing c:\python27\lib\site-packages\pykrige\uk.py
  Replacing c:\python27\lib\site-packages\pykrige\uk.pyc
  Replacing c:\python27\lib\site-packages\pykrige\variogram_models.py
  Replacing c:\python27\lib\site-packages\pykrige\variogram_models.pyc
Cleaning up...
  Removing temporary dir c:\users\ben\appdata\local\temp\pip_build_Ben...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\ben\\appdata\\local\\temp\\pip_build_Ben\\pykrige\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\ben\appdata\local\temp\pip-hnpeg6-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\ben\appdata\local\temp\pip_build_Ben\pykrige
Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 284, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pip\req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "C:\Python27\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\ben\\appdata\\local\\temp\\pip_build_Ben\\pykrige\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\ben\appdata\local\temp\pip-hnpeg6-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\ben\appdata\local\temp\pip_build_Ben\pykrige
```

Looks like the problem revolves around the file vcvarsall.bat; based on a quick Google search, this seems to be diagnostic of a compiler problem (see links below). Seems like telling Cython to use MinGW might be a doable work-around.

https://github.com/cython/cython/wiki/InstallingOnWindows

https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

https://support.enthought.com/hc/en-us/articles/204469210-Windows-Unable-to-find-vcvarsall-bat-cython-other-c-extensions-

**Comment by rth** [comment] 2015-09-08 19:27
Yes, you are right. The problem is there is no stable 64bit MinGW compiler (unless it chaged recently), as the page [CythonExtensionsOnWindows](https://github.com/cython/cython/wiki/CythonExtensionsOnWindows) mentions, under the section "Less usefull information". I suppose that asking users to install  a Microsoft Visual C++ compiler, just to build a those cython extensions is probably not a good idea. 

So I guess what could be done is to make this compilation optional on Windows, and fall back to the pure python implementations (which are not that much slower anyway) for the kriging algorithms if no compiler is found. That would probably be simpler, no? Or maybe fall back on windows 64bit and use MinGW for 32 bit installs? 

I can look into this, if necessary, but probably only next week.

**Comment by bsmurphy** [comment] 2015-09-08 20:00
I agree, making the compilation optional on Windows is a good way to deal with this. I probably won't be able to work on for the next few weeks; if you get a chance to look into it before I can get to it that would be great, otherwise I'll see what I can do at the end of the month.

**Comment by luismiguelbravo** [comment] 2015-09-08 20:22
Hello, thanks for replied

I will use a version of Windows 32-bit, with anaconda to complete the installation.
Is it possible to use a file 189000 data records with x, y and z values?
![image](https://cloud.githubusercontent.com/assets/5140529/9746176/36c800c4-5640-11e5-8a02-71c1c3d9bfc1.png)

and then create an grid with the krigin interpolation of Z values
it's possible with PyKrige?

**Comment by bsmurphy** [comment] 2015-09-08 20:31
That's a lot of points, but it is doable. You might just have to be patient. Using the moving window option might be a good idea, just be sure to set your variogram model appropriately (see my comment from May 26 in closed issue #2).

**Comment by rth** [comment] 2015-09-08 21:18
@bsmurphy no problem, I'll look into that next week.

@luismiguelbravo If you experience installation errors with `pip`, as a temporary solution you can install Microsoft Visual C++ Compiler for Python from [here](http://www.microsoft.com/en-us/download/details.aspx?id=44266) as explained in the [link](https://github.com/cython/cython/wiki/CythonExtensionsOnWindows) above. The compilation should work then.

**Comment by rth** [comment] 2016-07-20 15:32
Closing this issue as the corresponding problem was solved. The installation of Cython extensions on 64bit Windows can still be improved but that's a separate issue.

**Closed by rth** 2016-07-20 15:32 UTC
